### PR TITLE
remove colors

### LINKED ISSUE #2: remove color from http
Find a better way to color messages

### PR DESCRIPTION
**Pull request by inezabonte**
closes #2

### CODE REVIEW

**Comment by raae** [comment]
If you replace 
`const [loading, setLoading] = useState(false);`
with the status approach I used in the webinar
`const [status, setStatus] = useState('initial')`
then you could do something like 

```
const color = "blue";
if(status === "fulfilled") {
  color = "green";
} else if (status === "failed") {
  color = "red";
}
```

(FYI: did not test this code, so treat it like psudo code)

**Comment by inezabonte** [comment]
@raae The purpose of the `loading` state is to disable the button and the input so that 
the use does not press the button multiple times sending many requests at once

**Comment by raae** [comment]
Yes, you would then change that to `status==="pending"` (forgot to do that on the webinar).
And if you do not want to write it many times you can do `const isDisabled = status === "pending"` and then use `isDisabled`.

**Comment by raae** [comment]
But this is a preference thing. 
You could also do:
```
const [color, setColor] = useState("blue")
```
And then on sucess do `setColor("green")` and on error do `setColor("red")`.

**Comment by inezabonte** [comment]
I'll experiment with both options and see what works best

**Comment by raae** [comment]
If you want to geek out, here is an article [on stop using "isLoading"](https://kentcdodds.com/blog/stop-using-isloading-booleans) by Kent C. Dodds. I do not take such a hard stance though, choice like these always depends on the use case.

**Comment by inezabonte** [comment]
Haha yea true. It would be more suitable for larger projects

**Pull request merged**
